BookInformationSystem/Models/Domain/Publisher.cs
using System.ComponentModel.DataAnnotations;

namespace BookInformationSystem.Models.Domain
{
    public class Publisher
    {
        public int Id { get; set; }
        [Required]
        public string PublisherName { get; set; }
    }
}

BookInformationSystem/Controllers/PublisherController.cs
using BookInformationSystem.Models.Domain;
using BookInformationSystem.Repositories.Abstract;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookInformationSystem.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class PublisherController : Controller
    {
        private readonly IPublisherService service;
        public PublisherController(IPublisherService service)
        {
            this.service = service;
        }
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Publisher model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = service.Add(model);
            if (result)
            {
                TempData["msg"] = "Added Successfully";
                return RedirectToAction(nameof(Add));
            }
            TempData["msg"] = "Error has occured on server side";
            return View(model);
        }


        public IActionResult Update(int id)
        {
            var record = service.FindById(id);
            return View(record);
        }

        [HttpPost]
        public IActionResult Update(Publisher model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = service.Update(model);
            if (result)
            {
                return RedirectToAction("GetAll");
            }
            TempData["msg"] = "Error has occured on server side";
            return View(model);
        }


        public IActionResult Delete(int id)
        {

            var result = service.Delete(id);
            return RedirectToAction("GetAll");
        }

        public async Task<IActionResult> GetAll(string searchString, int page = 0)
        {

            var publisher = service.GetAll();

            if (!String.IsNullOrEmpty(searchString))
            {
                publisher = publisher.Where(s => s.PublisherName!.Contains(searchString));
            }

            const int PageSize = 3;

            var count = publisher.Count();

            var data = publisher.Skip(page * PageSize).Take(PageSize).OrderBy(s => s.PublisherName).ToList();

            this.ViewBag.MaxPage = (count / PageSize) - (count % PageSize == 0 ? 1 : 0);

            this.ViewBag.Page = page;
            return View(data);
        }
    }
}

BookInformationSystem/Views/Publisher/Add.cshtml
@model BookInformationSystem.Models.Domain.Publisher
@{
}

<div class="container pt-5">
    <div class="row">
        <div class="col-md-6">
            <h3>Add Publisher</h3>
            <form asp-action="Add" method="post">
                <div class="form-group">
                    <label asp-for="PublisherName">Publisher Name *</label>
                    <input type="text" class="form-control" asp-for="PublisherName"/>
                    <span asp-validation-for="PublisherName" class="text-danger"></span>
                </div>
                @if(TempData["msg"] != null)
                {
                    <div class="form-group">
                        @TempData["msg"]
                    </div>
                }
                <div class="form-group pt-3">
                    <button type="submit" class="btn btn-dark"><i class="bi bi-save p-1"></i>Save</button>
                    <a href="/Publisher/GetAll" class="btn btn-primary"><i class="bi bi-card-list p-1"></i>List</a>
                </div>
            </form>
        </div>
    </div>
</div>

BookInformationSystem/Views/Publisher/GetAll.cshtml
@model IEnumerable<BookInformationSystem.Models.Domain.Publisher>
@{
}

<div class="container pt-5">
    <div class="row p-3">
        <div class="col-8 text-left">
            <h3>Publisher</h3>
        </div>
        <div class="col-4 text-right ml-auto">
            <a class="btn btn-dark" href="/Publisher/Add">+ Add More</a>>
        </div>
        <form asp-controller="Publisher" asp-action="GetAll">
            <div class="input-group m-2">
                <input type="text" class="form-control" placeholder="Search" aria-label="Search" name="SearchString">
                <button class="btn btn-dark" type="submit">Search</button>
            </div>
        </form>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-dark">
            <thead>
                <tr>
                    <th>Publisher Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                    {
                        <tr>
                            <td>@item.PublisherName</td>
                            <td>
                                <a class="btn btn-success" href="/Publisher/Update?id=@item.Id"><i class="bi bi-pen"></i></a>
                                <a class="btn btn-danger" onclick="return window.confirm('Are you sure?')" href="/Publisher/Delete?id=@item.Id"><i class="bi bi-trash"></i></a>
                            </td>
                        </tr>
                    }
            </tbody>
        </table>
        <br />
        @if (ViewBag.Page > 0)
        {
            <a href="@Url.Action("GetAll", new { page = ViewBag.Page - 1 })"
           class="btn btn-default">
                &laquo; Prev
            </a>
        }
        @if (ViewBag.Page < ViewBag.MaxPage)
        {
            <a href="@Url.Action("GetAll", new { page = ViewBag.Page + 1 })"
           class="btn btn-default">
                Next &raquo;
            </a>
        }
        @if (!Model.Any())
        {
            <p class="text-muted text-center mt-4">No authors found.</p>
        }
    </div>
</div>

BookInformationSystem/Views/Publisher/Update.cshtml
@model BookInformationSystem.Models.Domain.Publisher
@{
}

<div class="container pt-5">
    <div class="row">
        <div class="col-md-6">
            <h3>Update Publisher</h3>
            <form asp-action="Update" method="post">
                <input type="hidden" asp-for="Id"/>
                <div class="form-group">
                    <label asp-for="PublisherName">Publisher Name *</label>
                    <input type="text" class="form-control" asp-for="PublisherName" />
                    <span asp-validation-for="PublisherName" class="text-danger"></span>
                </div>
                @if (TempData["msg"] != null)
                {
                    <div class="form-group">
                        @TempData["msg"]
                    </div>
                }
                <div class="form-group pt-3">
                    <button type="submit" class="btn btn-dark"><i class="bi bi-save p-1"></i>Update</button>
                    <a href="/Publisher/GetAll" class="btn btn-primary"><i class="bi bi-card-list p-1"></i>List</a>
                </div>
            </form>
        </div>
    </div>
</div>